-- EcoVolt - Script alinhado ao MER T_EV_*
-- Execute no Oracle SQL Developer

-- DROP (ordem inversa das FKs)
DROP TABLE T_EV_INTERACAO CASCADE CONSTRAINTS;
DROP TABLE T_EV_USU_CON CASCADE CONSTRAINTS;
DROP TABLE T_EV_USU_MIS CASCADE CONSTRAINTS;
DROP TABLE T_EV_OBJ_MIS CASCADE CONSTRAINTS;
DROP TABLE T_EV_LOGIN_DIARIO CASCADE CONSTRAINTS;
DROP TABLE T_EV_RECUPERACAO_LOGIN CASCADE CONSTRAINTS;
DROP TABLE T_EV_PONTUACAO CASCADE CONSTRAINTS;
DROP TABLE T_EV_CONTA_ENERGIA CASCADE CONSTRAINTS;
DROP TABLE T_EV_DICA CASCADE CONSTRAINTS;
DROP TABLE T_EV_USUARIO CASCADE CONSTRAINTS;
DROP TABLE T_EV_MISSAO CASCADE CONSTRAINTS;
DROP TABLE T_EV_CONQUISTA CASCADE CONSTRAINTS;
DROP TABLE T_EV_ACA_SUSTENTAVEIS CASCADE CONSTRAINTS;
DROP TABLE T_EV_RECOMPENSA CASCADE CONSTRAINTS;
DROP TABLE T_EV_NIVEL CASCADE CONSTRAINTS;
DROP TABLE T_EV_RANKING CASCADE CONSTRAINTS;

DROP SEQUENCE SQ_EV_INTERACAO;
DROP SEQUENCE SQ_EV_USU_CON;
DROP SEQUENCE SQ_EV_USU_MIS;
DROP SEQUENCE SQ_EV_OBJ_MIS;
DROP SEQUENCE SQ_EV_LOGIN_DIARIO;
DROP SEQUENCE SQ_EV_RECUPERACAO;
DROP SEQUENCE SQ_EV_PONTUACAO;
DROP SEQUENCE SQ_EV_CONTA_ENERGIA;
DROP SEQUENCE SQ_EV_DICA;
DROP SEQUENCE SQ_EV_USUARIO;
DROP SEQUENCE SQ_EV_MISSAO;
DROP SEQUENCE SQ_EV_CONQUISTA;
DROP SEQUENCE SQ_EV_ACAO;
DROP SEQUENCE SQ_EV_RECOMPENSA;
DROP SEQUENCE SQ_EV_NIVEL;
DROP SEQUENCE SQ_EV_RANKING;

-- NIVEL
CREATE TABLE T_EV_NIVEL (
    ID_NIVEL        NUMBER NOT NULL PRIMARY KEY,
    NM_NIVEL        VARCHAR2(50) NOT NULL,
    NR_XP_MINIMA    NUMBER NOT NULL,
    NR_XP_MAXIMA    NUMBER NOT NULL
);
CREATE SEQUENCE SQ_EV_NIVEL START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- RANKING
CREATE TABLE T_EV_RANKING (
    ID_RANK         NUMBER NOT NULL PRIMARY KEY,
    NM_RANK         VARCHAR2(50) NOT NULL,
    NR_POSICAO      NUMBER NOT NULL,
    DT_REFERENCIA   DATE NOT NULL
);
CREATE SEQUENCE SQ_EV_RANKING START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- USUARIO
CREATE TABLE T_EV_USUARIO (
    ID_USUARIO      NUMBER NOT NULL PRIMARY KEY,
    NM_USUARIO      VARCHAR2(100) NOT NULL,
    DS_EMAIL        VARCHAR2(100) NOT NULL,
    DS_SENHA        VARCHAR2(50) NOT NULL,
    DT_NASCIMENTO   DATE,
    DS_GENERO       VARCHAR2(20),
    DS_CIDADE       VARCHAR2(50),
    DS_ESTADO       VARCHAR2(2),
    DS_PAIS         VARCHAR2(50),
    QT_PONTOS       NUMBER(10) DEFAULT 0 NOT NULL,
    ID_NIVEL        NUMBER,
    ID_RANK         NUMBER,
    CONSTRAINT UK_EV_USUARIO_EMAIL UNIQUE (DS_EMAIL),
    CONSTRAINT FK_EV_USU_NIVEL FOREIGN KEY (ID_NIVEL) REFERENCES T_EV_NIVEL (ID_NIVEL),
    CONSTRAINT FK_EV_USU_RANK FOREIGN KEY (ID_RANK) REFERENCES T_EV_RANKING (ID_RANK)
);
CREATE SEQUENCE SQ_EV_USUARIO START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- LOGIN DIARIO
CREATE TABLE T_EV_LOGIN_DIARIO (
    ID_LOGIN        NUMBER NOT NULL PRIMARY KEY,
    ID_USUARIO      NUMBER NOT NULL,
    DT_LOGIN        DATE NOT NULL,
    CONSTRAINT FK_EV_LOGIN_USU FOREIGN KEY (ID_USUARIO) REFERENCES T_EV_USUARIO (ID_USUARIO)
);
CREATE SEQUENCE SQ_EV_LOGIN_DIARIO START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- RECUPERACAO LOGIN
CREATE TABLE T_EV_RECUPERACAO_LOGIN (
    ID_RECUPERACAO  NUMBER NOT NULL PRIMARY KEY,
    ID_USUARIO      NUMBER NOT NULL,
    DS_CODIGO       VARCHAR2(20) NOT NULL,
    DT_SOLICITACAO  DATE NOT NULL,
    ST_UTILIZADO    CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT FK_EV_REC_USU FOREIGN KEY (ID_USUARIO) REFERENCES T_EV_USUARIO (ID_USUARIO),
    CONSTRAINT CK_EV_REC_UTIL CHECK (ST_UTILIZADO IN ('S', 'N'))
);
CREATE SEQUENCE SQ_EV_RECUPERACAO START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- CONTA ENERGIA
CREATE TABLE T_EV_CONTA_ENERGIA (
    ID_CONTA_ENERGIA NUMBER NOT NULL PRIMARY KEY,
    ID_USUARIO       NUMBER NOT NULL,
    DT_REFERENCIA    DATE NOT NULL,
    NR_LEITURA       NUMBER,
    VL_CONSUMO_KWH   NUMBER(10,2) NOT NULL,
    VL_TOTAL_CONTA   NUMBER(10,2) NOT NULL,
    DS_COMPROVANTE   VARCHAR2(200),
    ST_PAGAMENTO     CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT FK_EV_CONTA_USU FOREIGN KEY (ID_USUARIO) REFERENCES T_EV_USUARIO (ID_USUARIO),
    CONSTRAINT CK_EV_CONTA_PAG CHECK (ST_PAGAMENTO IN ('S', 'N'))
);
CREATE SEQUENCE SQ_EV_CONTA_ENERGIA START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- PONTUACAO
CREATE TABLE T_EV_PONTUACAO (
    ID_PONTUACAO    NUMBER NOT NULL PRIMARY KEY,
    ID_USUARIO      NUMBER NOT NULL,
    DT_GANHO        DATE NOT NULL,
    QT_PONTOS       NUMBER NOT NULL,
    DS_MOTIVO       VARCHAR2(200),
    CONSTRAINT FK_EV_PONT_USU FOREIGN KEY (ID_USUARIO) REFERENCES T_EV_USUARIO (ID_USUARIO)
);
CREATE SEQUENCE SQ_EV_PONTUACAO START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- CONQUISTA
CREATE TABLE T_EV_CONQUISTA (
    ID_CONQUISTA      NUMBER NOT NULL PRIMARY KEY,
    NM_CONQUISTA      VARCHAR2(100) NOT NULL,
    DS_CONQUISTA      VARCHAR2(255),
    QT_PONTOS_PREMIO  NUMBER NOT NULL
);
CREATE SEQUENCE SQ_EV_CONQUISTA START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- USUARIO x CONQUISTA
CREATE TABLE T_EV_USU_CON (
    ID_USU_CON      NUMBER NOT NULL PRIMARY KEY,
    ID_USUARIO      NUMBER NOT NULL,
    ID_CONQUISTA    NUMBER NOT NULL,
    DT_CONQUISTA    DATE NOT NULL,
    CONSTRAINT FK_EV_USUCON_USU FOREIGN KEY (ID_USUARIO) REFERENCES T_EV_USUARIO (ID_USUARIO),
    CONSTRAINT FK_EV_USUCON_CON FOREIGN KEY (ID_CONQUISTA) REFERENCES T_EV_CONQUISTA (ID_CONQUISTA)
);
CREATE SEQUENCE SQ_EV_USU_CON START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- ACOES SUSTENTAVEIS
CREATE TABLE T_EV_ACA_SUSTENTAVEIS (
    ID_ACAO           NUMBER NOT NULL PRIMARY KEY,
    NM_ACAO           VARCHAR2(100) NOT NULL,
    DS_ACAO           VARCHAR2(255),
    QT_PONTOS_BASE    NUMBER NOT NULL
);
CREATE SEQUENCE SQ_EV_ACAO START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- MISSAO
CREATE TABLE T_EV_MISSAO (
    ID_MISSAO         NUMBER NOT NULL PRIMARY KEY,
    NM_MISSAO         VARCHAR2(100) NOT NULL,
    DS_MISSAO         VARCHAR2(255),
    QT_PONTOS_PREMIO  NUMBER NOT NULL,
    DT_INICIO         DATE,
    DT_FIM            DATE
);
CREATE SEQUENCE SQ_EV_MISSAO START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- OBJETIVO DA MISSAO
CREATE TABLE T_EV_OBJ_MIS (
    ID_OBJETIVO     NUMBER NOT NULL PRIMARY KEY,
    ID_MISSAO       NUMBER NOT NULL,
    DS_OBJETIVO     VARCHAR2(255) NOT NULL,
    QT_META         NUMBER,
    CONSTRAINT FK_EV_OBJ_MIS FOREIGN KEY (ID_MISSAO) REFERENCES T_EV_MISSAO (ID_MISSAO)
);
CREATE SEQUENCE SQ_EV_OBJ_MIS START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- USUARIO x MISSAO
CREATE TABLE T_EV_USU_MIS (
    ID_USU_MIS      NUMBER NOT NULL PRIMARY KEY,
    ID_USUARIO      NUMBER NOT NULL,
    ID_MISSAO       NUMBER NOT NULL,
    ST_STATUS       VARCHAR2(20) DEFAULT 'EM_ANDAMENTO' NOT NULL,
    CONSTRAINT FK_EV_USUMIS_USU FOREIGN KEY (ID_USUARIO) REFERENCES T_EV_USUARIO (ID_USUARIO),
    CONSTRAINT FK_EV_USUMIS_MIS FOREIGN KEY (ID_MISSAO) REFERENCES T_EV_MISSAO (ID_MISSAO)
);
CREATE SEQUENCE SQ_EV_USU_MIS START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- DICA
CREATE TABLE T_EV_DICA (
    ID_DICA           NUMBER NOT NULL PRIMARY KEY,
    NM_DICA           VARCHAR2(100) NOT NULL,
    DS_DICA           VARCHAR2(500) NOT NULL,
    ID_USUARIO_AUTOR  NUMBER NOT NULL,
    CONSTRAINT FK_EV_DICA_USU FOREIGN KEY (ID_USUARIO_AUTOR) REFERENCES T_EV_USUARIO (ID_USUARIO)
);
CREATE SEQUENCE SQ_EV_DICA START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- INTERACAO
CREATE TABLE T_EV_INTERACAO (
    ID_INTERACAO    NUMBER NOT NULL PRIMARY KEY,
    ID_USUARIO      NUMBER NOT NULL,
    ID_DICA         NUMBER NOT NULL,
    TP_INTERACAO    VARCHAR2(20) NOT NULL,
    DS_COMENTARIO   VARCHAR2(255),
    DT_INTERACAO    DATE NOT NULL,
    CONSTRAINT FK_EV_INT_USU FOREIGN KEY (ID_USUARIO) REFERENCES T_EV_USUARIO (ID_USUARIO),
    CONSTRAINT FK_EV_INT_DICA FOREIGN KEY (ID_DICA) REFERENCES T_EV_DICA (ID_DICA)
);
CREATE SEQUENCE SQ_EV_INTERACAO START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- RECOMPENSA
CREATE TABLE T_EV_RECOMPENSA (
    ID_RECOMPENSA     NUMBER NOT NULL PRIMARY KEY,
    NM_RECOMPENSA     VARCHAR2(100) NOT NULL,
    DS_RECOMPENSA     VARCHAR2(255),
    QT_PONTOS_CUSTO   NUMBER NOT NULL
);
CREATE SEQUENCE SQ_EV_RECOMPENSA START WITH 1 INCREMENT BY 1 NOCYCLE ORDER;

-- DADOS INICIAIS
INSERT INTO T_EV_NIVEL (ID_NIVEL, NM_NIVEL, NR_XP_MINIMA, NR_XP_MAXIMA)
VALUES (SQ_EV_NIVEL.NEXTVAL, 'Iniciante', 0, 99);
INSERT INTO T_EV_NIVEL (ID_NIVEL, NM_NIVEL, NR_XP_MINIMA, NR_XP_MAXIMA)
VALUES (SQ_EV_NIVEL.NEXTVAL, 'Intermediario', 100, 299);
INSERT INTO T_EV_NIVEL (ID_NIVEL, NM_NIVEL, NR_XP_MINIMA, NR_XP_MAXIMA)
VALUES (SQ_EV_NIVEL.NEXTVAL, 'Avancado', 300, 999);

INSERT INTO T_EV_RANKING (ID_RANK, NM_RANK, NR_POSICAO, DT_REFERENCIA)
VALUES (SQ_EV_RANKING.NEXTVAL, 'Bronze', 3, SYSDATE);
INSERT INTO T_EV_RANKING (ID_RANK, NM_RANK, NR_POSICAO, DT_REFERENCIA)
VALUES (SQ_EV_RANKING.NEXTVAL, 'Prata', 2, SYSDATE);
INSERT INTO T_EV_RANKING (ID_RANK, NM_RANK, NR_POSICAO, DT_REFERENCIA)
VALUES (SQ_EV_RANKING.NEXTVAL, 'Ouro', 1, SYSDATE);

COMMIT;
